disabled_rules:
- line_length
- type_body_length
opt_in_rules:
- array_init
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- empty_count
- explicit_init
- explicit_type_interface
- fatal_error_message
- first_where
- force_unwrapping
- implicit_return
- joined_default_parameter
- let_var_whitespace
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- object_literal
- operator_usage_whitespace
- overridden_super_call
- pattern_matching_keywords
- private_action
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_imports
- trailing_closure
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- vertical_whitespace
excluded:
